#!/usr/bin/env bash
set -euo pipefail

for bucket in */; do
  [[ -d "$bucket" ]] || continue
  [[ "${bucket:0:1}" = "." ]] && continue

  for prob_dir in "${bucket}"*/; do
    [[ -d "$prob_dir" ]] || continue
    ./build-problem "${prob_dir%/}"
  done
done
